# Properti Standar AndroidX
android.useAndroidX=true
android.enableJetifier=true

# SOLUSI UTAMA: Paksa Gradle menggunakan JDK 17 di Drive D
# Baris ini memastikan PowerShell tidak lagi memanggil Java 8 di Drive C
# org.gradle.java.home=D:/Android_Gradle_Cache/jdks/eclipse_adoptium-17-amd64-windows.2/jdk-17.0.17+20
# Memori dan opsi modern untuk Gradle daemon
# Mengaktifkan ParallelGC (lebih stabil untuk build Android) dan membuka akses modul Java
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -XX:+UseParallelGC --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED

# Optimasi Build Performance
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.caching=true

# Konfigurasi Kapt & Temporary Directory di Drive D
# Memastikan proses SQLite dan file temp tidak membebani Drive C
kapt.jvmargs=-Xmx1024m -Dorg.sqlite.tmpdir=D:/temp/sqlite -Djava.io.tmpdir=D:/temp/sqlite

# Kompatibilitas Kotlin & K2 Backend
kapt.use.k2=true
kotlin.compiler.jvmTarget=17